### ISSUE TITLE
User Class

### ISSUE THREAD

**Issue by fernandofreamunde** [fernandofreamunde/myTube#3]
#### Description
As a Guest I would like to be able to register into this website/project

#### Task
Create the user Resource for the moment we want to allow the following:
- [ ] have a registration form,
- [ ] have a login form,
- [ ] have a profile where username, password and email can be managed.
- [ ] have a logout button,
